CREATE DATABASE IF NOT EXISTS RESTAURANT;

USE RESTAURANT;

CREATE TABLE ACCOUNT (
    ID_ACCOUNT INT AUTO_INCREMENT PRIMARY KEY,
    NAME_ACCOUNT VARCHAR(100) NOT NULL,
    EMAIL_ACCOUNT VARCHAR(200) NOT NULL UNIQUE,
    PASSWORD_ACCOUNT VARCHAR(255) NOT NULL,
    TYPE_ACCOUNT ENUM ('WORKER', 'CLIENT') NOT NULL DEFAULT 'CLIENT'
);

CREATE TABLE CLIENT (
    ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
    NAME_CLIENT VARCHAR(100) NOT NULL,
    CPF_CLIENT VARCHAR(11) NOT NULL,
    NUMBER_CLIENT VARCHAR(11) NOT NULL,
    PHOTO_CLIENT VARCHAR(255) NOT NULL,  
    ID_ACCOUNT_FK INT, 
    FOREIGN KEY (ID_ACCOUNT_FK) REFERENCES ACCOUNT (ID_ACCOUNT) ON DELETE CASCADE
);

CREATE TABLE WORKER (
    ID_WORKER INT AUTO_INCREMENT PRIMARY KEY,
    NAME_WORKER VARCHAR(100) NOT NULL,
    REGISTRATION_WORKER VARCHAR(6) NOT NULL,
    ROLE_WORKER VARCHAR(100) NOT NULL,
    PHOTO_WORKER VARCHAR(255) NOT NULL,
    ID_ACCOUNT_FK INT, 
    FOREIGN KEY (ID_ACCOUNT_FK) REFERENCES ACCOUNT (ID_ACCOUNT) ON DELETE CASCADE
);

CREATE TABLE CATEGORY (
    ID_CATEGORY INT AUTO_INCREMENT PRIMARY KEY,
    NAME_CATEGORY VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCT (
    ID_PRODUCT INT AUTO_INCREMENT PRIMARY KEY,
    NAME_PRODUCT VARCHAR(100) NOT NULL,
    DESCRIPTION_PRODUCT VARCHAR(100) NOT NULL,
    PRICE_PRODUCT DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    PHOTO_PRODUCT VARCHAR(255) NOT NULL,
    STOCK_PRODUCT INT NOT NULL DEFAULT 0,
    ID_CATEGORY_FK INT,
    FOREIGN KEY (ID_CATEGORY_FK) REFERENCES CATEGORY (ID_CATEGORY) 
);
