<?php
    define('HOST','localhost');
    define('USER', 'root');
    define('PASS', '');
    define('BASE', 'RESTAURANT');

 $conn = new mysqli(HOST, USER, PASS);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$conn->query("CREATE DATABASE IF NOT EXISTS `" . BASE . "`");
if (!$conn->select_db(BASE)) {
    die("Error selecting database: " . $conn->error);
}

$sqlACCOUNT = " CREATE TABLE  if not exists ACCOUNT (
    ID_ACCOUNT INT AUTO_INCREMENT PRIMARY KEY,
    NAME_ACCOUNT VARCHAR(100) NOT NULL,
    EMAIL_ACCOUNT VARCHAR(200) NOT NULL UNIQUE,
    PASSWORD_ACCOUNT VARCHAR(255) NOT NULL,
    TYPE_ACCOUNT ENUM ('WORKER', 'CLIENT') NOT NULL DEFAULT 'CLIENT'
)"; 
$conn->query($sqlACCOUNT);

$sqlCLIENT = " CREATE TABLE  if not exists CLIENT (
    ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
    NAME_CLIENT VARCHAR(100) NOT NULL,
    CPF_CLIENT VARCHAR(11) NOT NULL,
    NUMBER_CLIENT VARCHAR(11) NOT NULL,
    PHOTO_CLIENT VARCHAR(255) NOT NULL,  
    ID_ACCOUNT_FK INT, 
    FOREIGN KEY (ID_ACCOUNT_FK) REFERENCES ACCOUNT (ID_ACCOUNT) ON DELETE CASCADE
)";
$conn->query($sqlCLIENT);

$sqlWORKER = " CREATE TABLE if not exists WORKER (
    ID_WORKER INT AUTO_INCREMENT PRIMARY KEY,
    NAME_WORKER VARCHAR(100) NOT NULL,
    REGISTRATION_WORKER VARCHAR(6) NOT NULL,
    ROLE_WORKER VARCHAR(100) NOT NULL,
    PHOTO_WORKER VARCHAR(255) NOT NULL,
    ID_ACCOUNT_FK INT, 
    FOREIGN KEY (ID_ACCOUNT_FK) REFERENCES ACCOUNT (ID_ACCOUNT) ON DELETE CASCADE
)";
$conn->query($sqlWORKER);

$sqlCATEGORY = " CREATE TABLE  if not exists CATEGORY (
    ID_CATEGORY INT AUTO_INCREMENT PRIMARY KEY,
    NAME_CATEGORY VARCHAR(100) NOT NULL
)";
$conn->query($sqlCATEGORY);

$sqlPRODUCT = " CREATE TABLE  if not exists PRODUCT (
    ID_PRODUCT INT AUTO_INCREMENT PRIMARY KEY,
    NAME_PRODUCT VARCHAR(100) NOT NULL,
    DESCRIPTION_PRODUCT VARCHAR(100) NOT NULL,
    PRICE_PRODUCT DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    PHOTO_PRODUCT VARCHAR(255) NOT NULL,
    STOCK_PRODUCT INT NOT NULL DEFAULT 0,
    ID_CATEGORY_FK INT,
    FOREIGN KEY (ID_CATEGORY_FK) REFERENCES CATEGORY (ID_CATEGORY) 
)";
$conn->query($sqlPRODUCT);
return $conn;

?>
